/*Exports three sets of static data used for UI development or testing. tripData is an array of mock trip records, each containing an ID, trip name, amount spent, travel date, destination, and the date the request was made—useful for populating tables or lists without calling an API. spendOptions is a predefined list of expense category options (with value codes and human-readable labels) intended for dropdown/select components when classifying travel expenses. taxIndicatorOptions provides a smaller set of options for selecting the applicable VAT/IVA tax indicator, also formatted for use in select inputs. */
export const tripData = [
  {
    id: 1,
    tripName: "Viaje a la playa",
    amount: 1250.75,
    date: "2025-02-15",
    destination: "Cancún, Quintana Roo",
    requestDate: "2025-03-01",
  },
  {
    id: 2,
    tripName: "Viaje a la montaña",
    amount: 2400.5,
    date: "2025-01-22",
    destination: "Valle de Bravo",
    requestDate: "2025-02-05",
  },
  {
    id: 3,
    tripName: "Viaje a la ciudad",
    amount: 1750.0,
    date: "2024-12-10",
    destination: "Ciudad de México",
    requestDate: "2024-12-28",
  },
  {
    id: 4,
    tripName: "Viaje al campo",
    amount: 3200.25,
    date: "2025-03-05",
    destination: "Rancho Los Álamos",
    requestDate: "2025-03-20",
  },
  {
    id: 5,
    tripName: "Viaje a la selva",
    amount: 4500.0,
    date: "2024-11-18",
    destination: "Chiapas",
    requestDate: "2024-12-05",
  },
  {
    id: 6,
    tripName: "Viaje al pueblo mágico",
    amount: 1800.5,
    date: "2025-02-28",
    destination: "San Miguel de Allende",
    requestDate: "2025-03-15",
  },
  {
    id: 7,
    tripName: "Viaje al desierto",
    amount: 3850.75,
    date: "2025-01-10",
    destination: "San Luis Potosí",
    requestDate: "2025-02-01",
  },
  {
    id: 8,
    tripName: "Tour gastronómico",
    amount: 2750.0,
    date: "2024-10-25",
    destination: "Oaxaca",
    requestDate: "2024-11-10",
  },
  {
    id: 9,
    tripName: "Viaje de negocios",
    amount: 5200.25,
    date: "2025-03-12",
    destination: "Monterrey",
    requestDate: "2025-03-25",
  },
  {
    id: 10,
    tripName: "Viaje cultural",
    amount: 2900.5,
    date: "2025-02-05",
    destination: "Querétaro",
    requestDate: "2025-02-20",
  },
];

export const spendOptions = [
  { value: "ALIF", label: "Alimentación" },
  { value: "CAPA", label: "Capacitación" },
  { value: "CPF", label: "Caseta" },
  { value: "FIDP", label: "Ficha de Depósito" },
  { value: "GAS", label: "Gasolina" },
  { value: "HTLP", label: "Hotel pagado" },
  { value: "LAUN", label: "Lavandería" },
  { value: "NDPR", label: "No deducible" },
  { value: "NDVA", label: "No deducible varios vale azul" },
  { value: "REAU", label: "Renta automóvil" },
  { value: "TCCF", label: "Taxi con comprobante fiscal" },
  { value: "TSCF", label: "Taxi sin comprobante fiscal" },
  { value: "TRAA", label: "Trans automóvil y/o autobus" },
  { value: "AIRP", label: "Vuelo pagado" },
];

export const taxIndicatorOptions = [
  { value: "V0", label: "IVA ACREDITABLE PAGADO 0%" },
  { value: "V7", label: "IVA ACREDITABLE PAGADO 16%" },
  { value: "VC", label: "IVA ACREDITABLE PAGADO 8%" },
];
