/*Exports a constant array called approvalsData that contains mock (dummy) data representing travel approval records. Each object in the array includes detailed information about a specific travel request, such as trip details (departure date, city, country, reason), approval and settlement status, refund amount and currency, as well as employee-related information (employee number, position, name, email, creditor number, and company). This dataset is likely used for local development, testing, or UI prototyping in the “Historial” page before integrating with a real backend API. */

export const approvalsData = [
  {
    id: 1,
    code: "0001",
    departureDate: "14/09/2025",
    city: "Cancún",
    country: "MX",
    reason: "Viaje de negocios",
    authorization: "Pendiente",
    checking: "A liquidar",
    refund: "$100",
    currency: "MXN",
    employee: "000001",
    position: "Gerente",
    name: "Juan Pérez",
    email: "juan.perez@mail.com",
    creditor: "123456",
    company: "EmpresaX",
  },
  {
    id: 2,
    code: "0002",
    departureDate: "20/09/2025",
    city: "Guadalajara",
    country: "MX",
    reason: "Conferencia",
    authorization: "Autorizado",
    checking: "Liquidado",
    refund: "$150",
    currency: "MXN",
    employee: "000002",
    position: "Analista",
    name: "María López",
    email: "maria.lopez@mail.com",
    creditor: "123457",
    company: "EmpresaY",
  },
  {
    id: 3,
    code: "0003",
    departureDate: "01/10/2025",
    city: "Monterrey",
    country: "MX",
    reason: "Capacitación",
    authorization: "Rechazado",
    checking: "No aplica",
    refund: "$0",
    currency: "MXN",
    employee: "000003",
    position: "Coordinador",
    name: "Carlos Sánchez",
    email: "carlos.sanchez@mail.com",
    creditor: "123458",
    company: "EmpresaZ",
  },
  {
    id: 4,
    code: "0004",
    departureDate: "05/10/2025",
    city: "Puebla",
    country: "MX",
    reason: "Reunión con cliente",
    authorization: "Pendiente",
    checking: "A liquidar",
    refund: "$80",
    currency: "MXN",
    employee: "000004",
    position: "Ejecutivo",
    name: "Ana Martínez",
    email: "ana.martinez@mail.com",
    creditor: "123459",
    company: "EmpresaA",
  },
  {
    id: 5,
    code: "0005",
    departureDate: "10/10/2025",
    city: "Toluca",
    country: "MX",
    reason: "Inspección",
    authorization: "Autorizado",
    checking: "Liquidado",
    refund: "$120",
    currency: "MXN",
    employee: "000005",
    position: "Supervisor",
    name: "Luis Fernández",
    email: "luis.fernandez@mail.com",
    creditor: "123460",
    company: "EmpresaB",
  },
  {
    id: 6,
    code: "0006",
    departureDate: "15/10/2025",
    city: "Querétaro",
    country: "MX",
    reason: "Proyecto especial",
    authorization: "Pendiente",
    checking: "En proceso",
    refund: "$200",
    currency: "MXN",
    employee: "000006",
    position: "Especialista",
    name: "Sofía Gómez",
    email: "sofia.gomez@mail.com",
    creditor: "123461",
    company: "EmpresaC",
  },
  {
    id: 7,
    code: "0007",
    departureDate: "20/10/2025",
    city: "Mérida",
    country: "MX",
    reason: "Auditoría",
    authorization: "Rechazado",
    checking: "No aplica",
    refund: "$0",
    currency: "MXN",
    employee: "000007",
    position: "Auditor",
    name: "Jorge Ramírez",
    email: "jorge.ramirez@mail.com",
    creditor: "123462",
    company: "EmpresaD",
  },
  {
    id: 8,
    code: "0008",
    departureDate: "25/10/2025",
    city: "Chihuahua",
    country: "MX",
    reason: "Visita técnica",
    authorization: "Autorizado",
    checking: "Liquidado",
    refund: "$170",
    currency: "MXN",
    employee: "000008",
    position: "Técnico",
    name: "Elena Torres",
    email: "elena.torres@mail.com",
    creditor: "123463",
    company: "EmpresaE",
  },
];
