/*Exports a constant array called TravelAgencyFormData containing mock data for travel agency requests. Each object represents a trip with details such as request ID, title, travel date, destination, request date, number of days, number of passengers, type of transport, total price, and current status (e.g., Aprobado, Pendiente, Rechazado). This dataset is likely used for local development or UI testing in the “Historial” section, allowing the interface to display sample travel agency records without relying on a backend API. */

export const TravelAgencyFormData = [
  {
    id: "0001",
    title: "Viaje a Cancún",
    travelDate: "14/09/2020",
    destination: "Cancún, MX",
    requestDate: "10/09/2020",
    days: 5,
    passengers: 2,
    transport: "Avión",
    price: 12000,
    status: "Aprobado",
  },
  {
    id: "0002",
    title: "Viaje a CDMX",
    travelDate: "20/10/2020",
    destination: "Ciudad de México, MX",
    requestDate: "15/10/2020",
    days: 3,
    passengers: 1,
    transport: "Autobús",
    price: 3500,
    status: "Pendiente",
  },
  {
    id: "0003",
    title: "Viaje a Monterrey",
    travelDate: "05/11/2020",
    destination: "Monterrey, MX",
    requestDate: "01/11/2020",
    days: 4,
    passengers: 3,
    transport: "Auto rentado",
    price: 8000,
    status: "Rechazado",
  },
];
